# Generated by Django 6.0 on 2025-12-17 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0004_remove_driver_city_driver_cities_alter_driver_car_and_more'),
        ('main', '0002_alter_city_id_alter_contact_id_alter_day_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_riders', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('rider_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reject_Comment', models.TextField(blank=True, null=True)),
                ('city', models.ManyToManyField(to='main.city')),
                ('days_of_week', models.ManyToManyField(to='main.day')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='drivers.driver')),
                ('end_neighborhood', models.ManyToManyField(related_name='trip_ends', to='main.neighborhood')),
                ('start_neighborhood', models.ManyToManyField(related_name='trip_starts', to='main.neighborhood')),
            ],
        ),
    ]
