# Generated by Django 5.2.7 on 2025-12-17 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_alter_car_id_alter_carcompany_id_alter_driver_id_and_more'),
        ('trips', '0002_alter_trip_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='creadted_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='drivers.driver'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='reject_Comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
