# Generated by Django 5.2.7 on 2025-12-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_alter_jointrip_id_alter_trip_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Rejection Reason'),
        ),
    ]
