# Generated by Django 6.0 on 2025-12-16 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '9665********' or '05********' (10 digits). Only digits allowed.", regex='^(9665\\d{8}|05\\d{8})$')]),
        ),
    ]
