# Generated by Django 6.0 on 2025-12-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_alter_car_id_alter_carcompany_id_alter_driver_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='car_registration',
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='carcompany',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reviewdriver',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
