# Generated by Django 6.0 on 2025-12-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_remove_driver_cities_driver_city_driver_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='car_registration',
            field=models.ImageField(blank=True, null=True, upload_to='images/car_registrations/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='licenses',
            field=models.ImageField(blank=True, null=True, upload_to='images/licenses/'),
        ),
    ]
