# Generated by Django 5.2.7 on 2025-12-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0010_alter_car_id_alter_carcompany_id_alter_driver_id_and_more'),
        ('drivers', '0010_reviewdriver_trip_alter_reviewdriver_rating_and_more'),
    ]

    operations = [
    ]
