# Generated by Django 5.2.7 on 2025-12-16 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('national_id_or_iqama', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='female', max_length=6)),
                ('avatar', models.ImageField(default='images/avatars/avatar.webp', upload_to='images/avatars/')),
                ('date_of_birth', models.DateTimeField()),
                ('size_car', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('larg', 'Larg')], default='medium', max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewRider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField()),
                ('comments', models.TextField()),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riders.rider')),
            ],
        ),
    ]
