# Generated by Django 6.0 on 2025-12-20 18:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_city_id_alter_contact_id_alter_day_id_and_more'),
        ('riders', '0002_alter_reviewrider_id_alter_rider_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='City',
        ),
        migrations.AlterField(
            model_name='reviewrider',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rider',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='size_car',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('larg', 'Larg')], default='medium', max_length=64),
        ),
        migrations.AddField(
            model_name='rider',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.city'),
        ),
    ]
