# Generated by Django 5.2.7 on 2025-12-17 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0002_remove_reviewrider_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rider',
            old_name='city',
            new_name='cities',
        ),
    ]
