# Generated by Django 6.0 on 2025-12-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0003_alter_reviewrider_id_alter_rider_id'),
        ('riders', '0003_rename_city_rider_cities'),
    ]

    operations = [
    ]
