# Generated by Django 5.2.7 on 2025-12-17 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0004_merge_20251217_1654'),
        ('riders', '0005_alter_reviewrider_id_alter_rider_id'),
    ]

    operations = [
    ]
