# Generated by Django 5.2.7 on 2025-12-24 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0009_alter_car_id_alter_carcompany_id_alter_driver_id_and_more'),
        ('riders', '0006_alter_reviewrider_id_alter_rider_id'),
        ('trips', '0009_alter_jointrip_id_alter_trip_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrider',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rider_reviews', to='trips.trip'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviewrider',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewrider',
            name='rating',
            field=models.SmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=3),
        ),
        migrations.AlterUniqueTogether(
            name='reviewrider',
            unique_together={('trip', 'rider', 'driver')},
        ),
    ]
