# Generated by Django 6.0 on 2025-12-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0007_alter_reviewrider_id_alter_rider_id'),
        ('riders', '0007_reviewrider_trip_alter_reviewrider_comments_and_more'),
    ]

    operations = [
    ]
