# Generated by Django 6.0 on 2025-12-21 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riders', '0003_remove_rider_city_alter_reviewrider_id_and_more'),
        ('trips', '0005_alter_jointrip_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('join_trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='trips.jointrip')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riders.rider')),
            ],
        ),
    ]
