# Generated by Django 6.0 on 2025-12-23 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_request', '0007_remove_joinrequesttrip_reject_comment_and_more'),
        ('trip_subscription', '0002_alter_tripsubscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripsubscription',
            name='join_request_trip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='rider_request.joinrequesttrip'),
        ),
        migrations.AlterField(
            model_name='tripsubscription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
