# Generated by Django 6.0 on 2025-12-24 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_subscription', '0003_alter_tripsubscription_id'),
        ('trip_subscription', '0003_tripsubscription_join_request_trip_and_more'),
    ]

    operations = [
    ]
