# Generated by Django 6.0 on 2025-12-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_subscription', '0005_merge_20251224_0759'),
        ('trip_subscription', '0005_merge_20251224_0930'),
        ('trip_subscription', '0005_merge_20251224_0932'),
        ('trip_subscription', '0007_alter_tripsubscription_join_request_trip_and_more'),
    ]

    operations = [
    ]
