# Generated by Django 6.0 on 2025-12-24 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_subscription', '0009_merge_20251224_2321'),
        ('trip_subscription', '0009_merge_20251224_2333'),
    ]

    operations = [
    ]
