# Generated by Django 5.2.7 on 2025-12-17 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_alter_city_id_alter_contact_id_alter_day_id_and_more'),
        ('riders', '0005_alter_reviewrider_id_alter_rider_id'),
        ('trips', '0003_rename_creadted_at_trip_created_at_trip_driver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_riders', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject')], default='reject', max_length=8)),
                ('accepted_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.city')),
                ('days_of_week', models.ManyToManyField(to='main.day')),
                ('end_neighborhood', models.ManyToManyField(related_name='rider_ends', to='main.neighborhood')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riders.rider')),
                ('start_neighborhood', models.ManyToManyField(related_name='rider_starts', to='main.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='CommentRiderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rider_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rider_request.riderrequest')),
            ],
        ),
    ]
