# Generated by Django 5.2.7 on 2025-12-19 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_request', '0001_initial'),
        ('trips', '0002_alter_trip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderrequest',
            name='accepted_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.trip'),
        ),
    ]
