# Generated by Django 5.2.7 on 2025-12-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_request', '0002_alter_riderrequest_accepted_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderrequest',
            name='status',
            field=models.CharField(choices=[('accept', 'Accept'), ('pending', 'Pending')], default='pending', max_length=8),
        ),
    ]
