# Generated by Django 6.0 on 2025-12-20 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_request', '0003_alter_riderrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentriderrequest',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='rider_request.commentriderrequest'),
        ),
        migrations.AlterField(
            model_name='commentriderrequest',
            name='rider_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='rider_request.riderrequest'),
        ),
    ]
