# Generated by Django 5.2.7 on 2025-12-21 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_alter_car_id_alter_carcompany_id_alter_driver_id_and_more'),
        ('rider_request', '0004_commentriderrequest_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderrequest',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.driver'),
        ),
    ]
